### ISSUE TITLE
Installation issues / clarifications [post here if you run into troubles]

### ISSUE THREAD

**Issue by vegu-ai** [vegu-ai/talemate#17]
General catch all ticket for installation issues in this early stage of development.

**Comment by Nroobz** [comment]
Hiya mate. I'm having trouble getting the API to be applied to all the agents.

**Comment by final-wombat** [comment]
@Nroobz hey - is it just assigning it to some agents and not all? What happens if you click the agent button under the client  ?
![image](https://github.com/final-wombat/talemate/assets/145254967/9c52d9a1-155a-4add-b8e0-742e98e65960)

**Comment by Nroobz** [comment]
@final-wombat when I click the agent button i.e 'creator', a modal window opens with a drop-down labelled 'client' but theres no data available for the the dropdown. 

error message below:

2023-11-19 17:29:38 [info     ] frontend connected
2023-11-19 17:29:38 [debug    ] frontend message               action_type=request_app_config
2023-11-19 17:29:38 [info     ] request_app_config
2023-11-19 17:30:14 [debug    ] frontend message               action_type=configure_clients
2023-11-19 17:30:14 [info     ] Configuring clients            clients=[{'name': 'TextGenWebUI', 'type': 'openai', 'apiUrl': 'http://localhost:5000', 'model_name': '', 'max_token_length': 4096, 'model': 'gpt-4-1106-preview'}]
2023-11-19 17:30:14 [error    ] Error connecting to client     client_name=TextGenWebUI e=TypeError("ClientBase.__init__() missing 1 required positional argument: 'api_url'")
server.py           :242  2023-11-19 17:30:14,387 connection handler failed
Traceback (most recent call last):
  File "D:\Git\TALEMATE\talemate-main\talemate_env\lib\site-packages\websockets\legacy\server.py", line 240, in handler
    await self.ws_handler(self)
  File "D:\Git\TALEMATE\talemate-main\talemate_env\lib\site-packages\websockets\legacy\server.py", line 1186, in _ws_handler
    return await cast(
  File "D:\Git\TALEMATE\talemate-main\src\talemate\server\api.py", line 115, in websocket_endpoint
    handler.configure_clients(data.get("clients"))
  File "D:\Git\TALEMATE\talemate-main\src\talemate\server\websocket_server.py", line 210, in configure_clients
    self.connect_llm_clients()
  File "D:\Git\TALEMATE\talemate-main\src\talemate\server\websocket_server.py", line 83, in connect_llm_clients
    self.connect_agents()
  File "D:\Git\TALEMATE\talemate-main\src\talemate\server\websocket_server.py", line 99, in connect_agents
    client = list(self.llm_clients.values())[0]["client"]
KeyError: 'client'
server.py           :268  2023-11-19 17:30:14,388 connection closed
server.py           :646  2023-11-19 17:30:14,735 connection open
2023-11-19 17:30:14 [info     ] frontend connected
2023-11-19 17:30:14 [debug    ] frontend message               action_type=request_app_config
2023-11-19 17:30:14 [info     ] request_app_config

**Comment by final-wombat** [comment]
```
2023-11-19 17:30:14 [info ] Configuring clients clients=[{'name': 'TextGenWebUI', 'type': 'openai', 'apiUrl': 'http://localhost:5000', 'model_name': '', 'max_token_length': 4096, 'model': 'gpt-4-1106-preview'}]
```

@Nroobz can you open the client config and change the type from openai to textgenwebui - looks like the types got mixed up and its failing to save the client because of it

Once the client is setup correctly it should actually auto assign it self to all agents if its the only client. Then there is also the button in the client row that will assign it to all agents on click as well:

![image](https://github.com/final-wombat/talemate/assets/145254967/1528ba5a-ef02-4822-bd38-4304b7038d22)

**Comment by final-wombat** [comment]
Seems like editing clients in generally seems sorta buggy atm, especially if you change the type on an existing client, created a bug ticket and will work on that.

I can't even remove the edited client now. 

I had to shutdown the backend and frontend and edit the config.yaml file to fix it. Let me know if you want to try that / need help with that.

**Comment by final-wombat** [comment]
Found all sorts of issues looking into this, [version 0.13.2 ](https://github.com/final-wombat/talemate/releases/tag/0.13.2) should fix it - let me know if not.

**Comment by Nroobz** [comment]
ok i'll get back to you asap with feedback

**Comment by Antrisa** [comment]
\Desktop\Ai chat thing\talemate-0.16.0\talemate-0.16.0\src\talemate\server\run.py", line 6, in <module>
    import structlog
ModuleNotFoundError: No module named 'structlog'

**Comment by vegu-ai-tools** [comment]
@Antrisa Odd, try to run `install.bat` again and see if it reports any errors.

**Comment by Antrisa** [comment]
> @Antrisa Odd, try to run `install.bat` again and see if that reports any errors. Since it can't find structlog i am expecting that the install script failed somewhere.

Note: This error originates from the build backend, and is likely not a problem with poetry but with safetensors (0.4.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "safetensors (==0.4.1)"'.

  • Installing scipy (1.11.4): Installing...
  • Installing starlette (0.27.0)
  • Installing threadpoolctl (3.2.0)
  • Installing tokenizers (0.15.0): Failed

  ChefBuildError


the installer also says maybe because pip is 23.2. not 23.3
but the zip I have to update pip doesn't work?


ehat exactly are all the steps in detail to do before a user should press install.bat

**Comment by vegu-ai-tools** [comment]
@Antrisa able to reproduce, looks like it is indeed missing some setup steps, will update once i know more

**Comment by vegu-ai-tools** [comment]
Meh, ok so i found two issues, i am not sure which one applies to your case but,

- python3.12 won't work, python3.10 and python3.11 do (downgrading to either fixes the issue for me)
- you may also need to install https://visualstudio.microsoft.com/visual-cpp-build-tools/ to grab up a newer version of microsoft c++ (but it should show you a very vocal message during install in this case telling you Microsoft Visual C++ needs to be 14.0 or higher)

**Comment by vegu-ai-tools** [comment]
0.16.1 released for some fixes to the install script for windows installations

**Comment by GabrielxScorpio** [comment]
Hello I am pretty new to this so this may be a dumb question.
I Installed a fresh Python 3.10.11, Node.js 21.6.1, and Talemate v0.18.0. When I started the bat file It gives me this error code:

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Program Files\nodejs\node_modules\npm\node_modules\strip-ansi\index.js from C:\Program Files\nodejs\node_modules\npm\node_modules\wide-align\node_modules\string-width\index.js not supported.
Instead change the require of C:\Program Files\nodejs\node_modules\npm\node_modules\strip-ansi\index.js in C:\Program Files\nodejs\node_modules\npm\node_modules\wide-align\node_modules\string-width\index.js to a dynamic import() which is available in all CommonJS modules.
at Object. (C:\Program Files\nodejs\node_modules\npm\node_modules\wide-align\node_modules\string-width\index.js:2:17) {
code: 'ERR_REQUIRE_ESM'
}

I tried restarting and reinstalling everything but I'm not sure how to fix it.

**Comment by vegu-ai-tools** [comment]
Hi @GabrielxScorpio 

Personally i had nodejs v19 installed, upgraded to v21 now and it seems to work correctly.

Can you do the following please:

- windows key + r to open the run program prompt
- enter `cmd` hit enter
- type `node -v`
- does it actually show v21 installed?

**Comment by GabrielxScorpio** [comment]
Thank you @vegu-ai-tools

I downgraded, and it worked!
I have gotten everything up to the point of loading the Infinity Quest and LM Studio. My issue now is getting a response from the AI. I tried multiple models on LM Studio, but after everything is loaded and I put any kind of input, it comes back with
 "Unhandled Error: unsupported operand type(s) for -: 'NoneType' and 'int'"

<img width="1256" alt="Problem LM Studio Talemate 1" src="https://github.com/vegu-ai/talemate/assets/151869808/87ae4eb7-b5f8-4b0d-8453-36281d66e786">

**Comment by vegu-ai-tools** [comment]
@GabrielxScorpio Odd

I've seen that error before, i think its an unhandled error when the AI returns an empty response on dialogue generation, maybe.

Although right now with LMStudio 0.2.12 loaded - using the same model - i can't reproduce it.

In the LMStudio view there should be a server log ticking by, what does it show when you trey to generate dialogue?

I'd expect it to look something like this:

![image](https://github.com/vegu-ai/talemate/assets/152010387/3601395d-f518-40b2-ba21-50c3edff9235)

**Comment by vegu-ai-tools** [comment]
@GabrielxScorpio oh i think i see the issue

![image](https://github.com/vegu-ai/talemate/assets/152010387/25544a7c-e3bb-4189-b2f8-0115061064ab)

It seems like the context size for the client isn't set to anything - can you try setting it either via the slider or via the client settings dialogue?

**Comment by GabrielxScorpio** [comment]
@vegu-ai-tools 
On Talemate, I tried moving the slider and changing the value from the settings, but it just forced it back to nothing, no number. 

This is my Lm Studio page.

![Full LM Error 1](https://github.com/vegu-ai/talemate/assets/151869808/b02ba8f0-4ac7-424b-b0de-84d59f6d21cc)

This is a closer look at the log. Every couple of seconds, it repeats that.

![Lm studio log error 1](https://github.com/vegu-ai/talemate/assets/151869808/1e7e661a-43c2-4eff-94d7-dc16a08d11e0)

This is what is showing up on the Talemate backend window every time the error appears.

![Talemate backend error message](https://github.com/vegu-ai/talemate/assets/151869808/d84196fc-b473-45c9-b4a4-cfd43841702a)

**Comment by vegu-ai-tools** [comment]
@GabrielxScorpio fix released in https://github.com/vegu-ai/talemate/releases/tag/0.18.1

Hope this fixes the issue for you as well. Apologies for the rough start, personally i dont run against LM Studio so testing against it has been somewhat neglected.

**Comment by GabrielxScorpio** [comment]
@vegu-ai-tools The update fixed the error! Thank you. 

I found another bug maybe? I had switched to using GPT4 turbo before your fix was released and it was not letting me continue with dialogue. But when I progress the story it answers back normally.

<img width="1145" alt="GPT4turbo error" src="https://github.com/vegu-ai/talemate/assets/151869808/2432a1b8-f36e-461a-804b-ac9fdafb19ff">

**Comment by vegu-ai-tools** [comment]
Woah, ill have to look at that - that's gpt-4 censoring itself. Given that there is nothing in the chat history that is even close to risky, it must be tripping over the system message talemate sends. I use gpt-4 turbo all the time so that's new if so. Thanks for pointing it out.

**Comment by thephilluk** [comment]
Hi there,
unsure if this is an installation error or (more likely) an user Error.
I am trying to use Talemate with the Chub AI.
but when entering the Data the Model isn't fetched and the following Error is printed in the Server Console (API Key changed):
```
2024-02-06 23:45:09 [info     ] Configuring clients            clients=[{'name': 'OpenAI Compatible API', 'type': 'openai_compat', 'api_url': 'https://mercury.chub.ai/mythomax/v1', 'model_name': 'mythomax', 'max_token_length': 4096, 'data': {}, 'model': 'mythomax', 'api_key': 'CHK-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'}]
server.py           :242  2024-02-06 23:45:09,609 connection handler failed
Traceback (most recent call last):
  File "C:\AI\talemate-0.19.0\talemate_env\Lib\site-packages\websockets\legacy\server.py", line 240, in handler
    await self.ws_handler(self)
  File "C:\AI\talemate-0.19.0\talemate_env\Lib\site-packages\websockets\legacy\server.py", line 1186, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "C:\AI\talemate-0.19.0\src\talemate\server\api.py", line 119, in websocket_endpoint
    handler.configure_clients(data.get("clients"))
  File "C:\AI\talemate-0.19.0\src\talemate\server\websocket_server.py", line 233, in configure_clients
    self.connect_llm_clients()
  File "C:\AI\talemate-0.19.0\src\talemate\server\websocket_server.py", line 97, in connect_llm_clients
    client = self.llm_clients[client_name]["client"] = instance.get_client(
                                                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\talemate-0.19.0\src\talemate\instance.py", line 55, in get_client
    client = cls(name=name, *create_args, **create_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\talemate-0.19.0\src\talemate\client\openai_compat.py", line 33, in __init__
    super().__init__(**kwargs)
  File "C:\AI\talemate-0.19.0\src\talemate\client\base.py", line 95, in __init__
    self.set_client(max_token_length=self.max_token_length)
  File "C:\AI\talemate-0.19.0\src\talemate\client\openai_compat.py", line 41, in set_client
    self.client = AsyncOpenAI(base_url=self.api_url + "/v1", api_key=self.api_key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\talemate-0.19.0\talemate_env\Lib\site-packages\openai\_client.py", line 296, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
server.py           :268  2024-02-06 23:45:09,612 connection closed
server.py           :646  2024-02-06 23:45:09,960 connection open
2024-02-06 23:45:09 [info     ] frontend connected
```

**Comment by vegu-ai-tools** [comment]
@thephilluk the client auto-appends the `/v1` path to the url - try removing that (so `https://mercury.chub.ai/mythoma`)

That's the only thing that jumps out at me.

That said the OpenAI compat client is fairly fresh and has received very limited testing, so its probably still finnicky. Let me know if fixing the url doesn't do anything.

**Comment by vegu-ai-tools** [comment]
@thephilluk i went ahead and checked against their api and eventually got it working - however i think there is definitely something broken / fragile with the client, which i will look into as part of #76, but after saving and retrying a couple times it ended up working. (see my client config below)

Bad news - from the little i testing i did with it just now, i am not sure their mythomax instance is on par with what is required to handle the more demanding parts (specifically world state stuff, which requires a lot of JSON accuracy tasks) in talemate. So might not even be worth pursuing further at this point, seems like the experience will be supoptimal, alas.

![image](https://github.com/vegu-ai/talemate/assets/152010387/06ddacb3-127b-48c2-94d3-612c0542b229)

**Comment by thephilluk** [comment]
@vegu-ai-tools Got it, thank you!
what service do you recommend for people with weaker PCs?

**Comment by vegu-ai-tools** [comment]
@thephilluk good question :)

Personally i run local / rented gpu / official openai 

I have not had the time to test with any other remote apis so can't make any direct recommendations, but anything hosting a 7B mistral or upwards should be capable of handling talemate, keeping in mind that until #76 is fixed, the issues we just ran into with chub.ai for setup may still exist on those apis as well. 

Here is a list of models i currently test with (ranging 7B to 50B), that are all good

```
Kunoichi-7B
sparsetral-16x7B
Fimbulvetr-10.7B
dolphin-2.7-mixtral-8x7b
Mixtral-8x7B-instruct
```

Talemate does come with direct runpod support if you want to try the gpu rental route, but there is some setup involved, instructions here if you're interested: https://github.com/vegu-ai/talemate/blob/main/docs/runpod.md

**Comment by maxcurrent420** [comment]
Getting an error on the install script in Linux. It fails to install triton.

source install.sh
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
bash: talemate_env/bin/activate: No such file or directory

[installs other dependencies]

`
  - Installing triton (2.2.0): Failed

  RuntimeError

  Hash for triton (2.2.0) from archive triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl not found in known hashes (was: sha256:63f9fbd31ba01fab81a80334d963e28da8e2f5d4ba532b71c62246d7ba5ddf12)

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/executor.py:808 in _validate_archive_hash
      804│ 
      805│         archive_hash = f"{hash_type}:{get_file_hash(archive, hash_type)}"
      806│ 
      807│         if archive_hash not in known_hashes:
    → 808│             raise RuntimeError(
      809│                 f"Hash for {package} from archive {archive.name} not found in"
      810│                 f" known hashes (was: {archive_hash})"
      811│             )
      812│ 

Cannot install triton.
`

I tried removing the lock file, deleting the poetry cache, re-installing poetry all to no avail so far. 

Also, thanks for your hard work!

**Comment by vegu-ai-tools** [comment]
@maxcurrent420 looks like this might be an oversight in the linux install.sh script

```
Command 'python' not found, did you mean:
command 'python3' from deb python3
command 'python' from deb python-is-python3
bash: talemate_env/bin/activate: No such file or directory
```

The issue appears to be its never actually creating the virtual env.

can you try editing the file and changing `python` to `python3` and then running it again.

So 

```
python3 -m venv talemate_env
```

instead of

```
python -m venv talemate_env
```

**Comment by maxcurrent420** [comment]
> @maxcurrent420 looks like there are multiple things going on here
> 
> ```
> Command 'python' not found, did you mean:
> command 'python3' from deb python3
> command 'python' from deb python-is-python3
> bash: talemate_env/bin/activate: No such file or directory
> ```
> 
> first issue appears to be its never actually creating the virtual env.
> 
> can you try editing the file and changing `python` to `python3` and then running it again.
> 
> i think your case poetry just rolls a venv on its own anyways, so unsure this would do anything for your error, but still worth trying to see what happens if the first error is resolved, since it actually does a fresh poetry install into that venv.
> 
> I am not able to reproduce - this does scream poetry cache issue to me, but sounds like you already went down that path, so not sure.
> 
> one thing you could try is switching to the `prep-0.23.0` branch and try running it through docker.
> 
> Edit: did a bunch of edits for clarity

I did change it to python3 but what I ended up doing is installing structlog manually, followed by each other dependency after trying and getting a dependency error. Wasn't too bad.

**Comment by vegu-ai-tools** [comment]
Hi @Pixelycia - some users have report issues with the current docker setup, i believe this is a fault on our side and i will look at it shortly, thanks. Issue is tracked at https://github.com/vegu-ai/talemate/issues/114.

**Comment by vegu-ai-tools** [comment]
@Pixelycia please  check out the latest release (0.25.4) and see if that fixes the issue for you - you will need to run `docker compose build`  to rebuild or start from a fresh clone.

**Comment by MiyeonLin** [comment]
When using automatic1111 with a weak pc, i got into issues with timeout if my pc is slow in generating images, so i had to adjust the timeout, is there a failsafe to keep retrying until we get an image? Also can add options to change the sampler index for some models?

**Comment by vegu-ai-tools** [comment]
> When using automatic1111 with a weak pc, i got into issues with timeout if my pc is slow in generating images, so i had to adjust the timeout, is there a failsafe to keep retrying until we get an image? Also can add options to change the sampler index for some models?

Thanks for the feedback, added two new tickets to track this request

- https://github.com/vegu-ai/talemate/issues/142
- https://github.com/vegu-ai/talemate/issues/143

I personally use ComfyUI so i havent looked at A1111 in a while - if A1111 users can list some the most vital things to expose in the ticket that'd be helpful - with the caveat that i want to avoid overloading the agent config UX in talemate with options, so id prefer to be picky what to add.

**Comment by MiyeonLin** [comment]
When I get back home, I'll add some suggestions, been trying out comfyui too and having fun learning the underlying mechanism of using adetailer but I think most people who will be using this would prefer to use auto1111 due to the gui.

**Comment by InfernoSuperNova** [comment]
I'm bashing my head against the wall here. For starters, I modified install.sh to specify python 3.10/3.11 as I don't want to mess up my system python version. After installing, it tells me that I don't have structlog. Easy fix, just pip install that. I try again, I get the same issue with websockets. Once again, an easy fix. So I try again, and this time, it tlls me I don't have the module talemate, which isn't something that can be solved with pip install. Is there something I missed? There aren't any errors in the installation, there's a few warnings about vulnerabilities, but that's it.

**Comment by vegu-ai-tools** [comment]
@InfernoSuperNova i haven't tested against LMStudio in a while, but its definitely odd that it receives the request from talemate, yet talemate gets a connection error. Alas don't have an answer for you currently, but will make sure to test LMStudio as part of the 0.29 release.

**Comment by TomLucidor** [comment]
Using the Linux method @Pixelycia might try the Docker method later
```
error: Distribution `torch==2.8.0+cu128 @ registry+https://download.pytorch.org/whl/cu128` can't be installed because it doesn't have a source distribution or wheel for the current platform

hint: You're on macOS (`macosx_15_0_arm64`), but `torch` (v2.8.0+cu128) only has wheels for the following platforms: `manylinux_2_28_x86_64`, `win_amd64`; consider adding "sys_platform == 'darwin' and platform_machine == 'arm64'" to `tool.uv.required-environments` to ensure uv resolves to a version with compatible wheels
```
